### ISSUE TITLE
pyconkr-script/2018-05-meet-up/파이썬 개발환경 구성하기의 끝판왕 Docker Compose - 김승호.txt

### ISSUE THREAD

**Issue by golony6449** [pythonkr/pyconkr-script#15]
테스트를 위한 이슈입니다.

**Comment by syohnet** [comment]
적어주신대로 이슈제목에 파일 path를 표시하는 것도 좋네요!

`2018-05-meet-up/파이썬 개발환경 구성하기의 끝판왕 Docker Compose - 김승호.txt`

**Comment by golony6449** [comment]
@ohahohah 
그러면 파일 경로 전체를 이슈 제목으로 하는 것으로 이슈 템플릿 작성해볼게요.
