### ISSUE TITLE
자막표기규칙 contribution guide 작성

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#16]
[자막표기규칙 subtitle-notation.md](https://github.com/pythonkr/pyconkr-script/blob/master/subtitle-notation.md) 기여가이드 작성이 필요합니다.
- [ ] contribution guide 에 추가
- [x] PR template 생성
- [ ] issue template  생성

**Comment by golony6449** [comment]
PR 템플릿은 [이걸로](https://github.com/pythonkr/pyconkr-script/blob/draft/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) 일단 마무리해도 될까요?

**Comment by syohnet** [comment]
자막표기 규칙은 직접하면서 조금씩 수정하는게 많아서 pr 로 진행하면 번거로울 것 같습니다. 자막편집 작업을 진행해보고 wiki 로 바꾸는 것도 고려해보아요!

**Comment by golony6449** [comment]
넵넵, 그러면 우선은 편집 진행하면서 논의하고 마스터에 바로 푸시하는 것으로 할게요.

**Comment by syohnet** [comment]
자막표시규칙은 메인테이너가 관리하도록 하고 종료합니다. contribution 필요가 있을 경우 이슈 재생성.
