### ISSUE TITLE
contributor 를 README.md 에 노출합시다!

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#19]
- bot 사용해서 contributor 를 자동으로 업데이트! https://github.com/all-contributors/all-contributors-bot

**Comment by golony6449** [comment]
@ohahohah 
오. 이런 기능도 있군요.
혹시 제가 해봐도 될까요? 뭔가 직접 적용해보고 싶습니다.

**Comment by golony6449** [comment]
@ohahohah 
일단 봇은 적용 했습니다. 다만, 이게 PR을 머지 하면 짠 하고 나오는건 아닌것 같습니다.
cli를 사용하거나, 봇을 사용하거나 PR과 별도의 명령이 필요한것 같습니다.

bot: 이슈, PR 어디에든 코멘트 작성란에 작성 (어느정도의 자연어 처리 가능)
> `@all-contributors please add <username> for <contributions>`

cli
> yarn all-contributors add <username> <contributions>
> yarn all-contributors generate

cli는 `npm`이나 `yarn`이 필요해서 봇으로 하는것이 더 편리해 보입니다.

(앗, 여기에도 반응을 하네요;;)

**Comment by syohnet** [comment]
PR이 반영될 때 bot 에 comment 해서 기여자로 추가하는게 좋을 거 같습니다.

**Comment by golony6449** [comment]
그러면 머지할때 저희가 직접 코멘트 하는거로 하겠습니다.
(또 봇이 PR을 만들어 주는거라 어차피 머지는 직접 해야될것이라 생각됩니다.)

이모지 남겨주시면 이 이슈는 닫을게요 ㅎㅎ

**Comment by syohnet** [comment]
@all-contributors please add @golony6449  for projectManagement

**Comment by syohnet** [comment]
지금까지 컨트리뷰션 한 사람들을 위한 contributor bot  소환 
@all-contributors please add @chukycheese   for projectManagement.
@all-contributors please add @emscb  for projectManagement.
@all-contributors please add @cmygray  for projectManagement.
