### ISSUE TITLE
자막 작업: 2019-pyconkr/day2/김성현_리얼월드 메타클래스.txt

### ISSUE THREAD

**Issue by golony6449** [pythonkr/pyconkr-script#21]
## 작업 내용

* 기여하시려는 파일 이름 (이슈 이름에도 추가해주세요. ^^): pyconkr-script/2019-pyconkr/day2/김성현_리얼월드 메타클래스.txt

* 예상 마무리 일자: 03월 14일

## 생성 전 확인!

* 체크리스트를 확인해주세요. (체크하면서 확인하시면 편리합니다.)

- [x] 이슈 제목은 작업하려는 파일 이름으로 작성하셨나요?
- [x] `assignee`를 자신으로 할당 하셨나요?
- [x] `자막 스크립트 편집` 라벨이 추가되어있나요?

**Comment by syohnet** [comment]
@golony6449 안녕하세요, 해당 이슈를 작업 중이신가요? 예상 마무리 일자를 업데이트 해주시면 감사하겠습니다. 업데이트가 없으면 1주일 후 3/25 에 본 이슈는 종료하도록 하겠습니다.

**Comment by syohnet** [comment]
업데이트가 없어 이슈 종료합니다
