### ISSUE TITLE
contribution guide 통합

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#28]
contribution guide 작성 마무리되면 contribute file 하나로 합치는 건 어떻게 생각하시나요? README 에는  CONTRIBUTE.md 파일 링크만 걸어두고요. 
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file

_Originally posted by @ohahohah in https://github.com/pythonkr/pyconkr-script/issues/3#issuecomment-592942087_

**Comment by syohnet** [comment]
@golony6449 의견 부탁드립니다~

**Comment by golony6449** [comment]
@ohahohah 
네 좋습니다. `all-contributors`를 Readme에 넣고보니 다른 내용이 조금 길어보이긴 하더라구요.

readme에 있는 `스크립트 편집` 문단도 함께 넣고, readme에는 기여자랑 링크만 있으면 좋을것 같습니다.

**Comment by syohnet** [comment]
네 곧 파이콘 한국 블로그에 발행될 문자통역 소개글 링크도 나중에 README.md 에 붙여둘게요!
