### ISSUE TITLE
스크립트편집 contribution guide 작성

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#3]
- 수준 : git은 사용해봤으나, 컨트리뷰션과 PR 경험이 없는 사용자
- 순서: 문자통역 스크립트 수정 -> 유투브 자막 입력
- 내용: 문자통역 스크립트 검수에 대한 contribution

**목차**
- 사전 준비 #7 
   - local setting (cli  명령어 / fork, git clone 등) - [참고](https://github.com/pythonkr/pyconkr#getting-started)
   - 작업 전 issue 생성 
   - branch 세팅 
      - branch 명 형식, branch 를 forked project 에 생성  
 - 스크립트 수정 작업가이드 (용어집 참고,...) #9 
 - 작업완료 내용 PR 하기 #8 
   - 작업한 곳까지 PR 하는 방법 (어디까지 PR)

**Repository 세팅** 
- #5 
- #6

**Comment by iz4blue** [comment]
저의 교영님과 이야기 하는 것은 21자 로 이야기 하고 있습니다. :)

**Comment by syohnet** [comment]
@golony6449 컨트리뷰션 가이드는 여기서 thread 로 이야기해볼까요?

**Comment by golony6449** [comment]
아 그러면, 일단은 자막검수 작업을 하고, 그 다음 유투브에서 싱크작업을 하는건가요?

**Comment by syohnet** [comment]
네 저는 그렇게 생각하고 있습니다. 
- 자막검수 -> 유투브 싱크작업 
- 자막검수자와 유투브 싱크작업자는 같지 않아도 됨. 

유투브 자막작업시에도 검수한 스크립트를 사용하도록 하고요. 유투브 자막작업을 바로 시작해도 상관은 없지만 여러 사람들이 오류를 잡아내기에는 텍스트 스크립트가 좋을 거 같아요. 유투브 자막이 잘못된 걸 알려면 유투브 영상을 보거나 유투브 자막 스크립트 생성을 해서 보아야하니까요. 

저 순서로 갔을때 제가 우려되는 점은 
- 유투브 자막작업에서 오타 수정 -> 다시 자막 스크립트 업데이트 가 귀찮다
- 영상보면서 텍스트형태 자막 스크립트 수정하기가 힘들다. (타임태그가 없어서 보고자 하는 시간대로 이동해서 보기 힘듦. 예를 들면, 'docker에서는 컨테이너를 사용합니다'(텍스트) 가 영상에서 몇분몇초에 있는지 찾으려면 영상을 다 봐야하는 경우도 생길 수 있으니까요 )

**Comment by syohnet** [comment]
자막스크립트에 타임태그가 없어서 영상 위치 찾기 힘든 문제는  
유투브 자동생성 자막과 문자통역 스크립트 원본을 비교하면서 보면 좀 해결될까요?

**Comment by golony6449** [comment]
아.. 맞아요. 수정하는 부분때문에 스크립트가 먼저 처리되야 될것같다는 생각은 하고 있었습니다.

그리고 말씀하신 영상 위치부분은 내용 검수는 함께 하되,
캡션 작업은 한명이 할 것 같아서 큰 문제가 되지는 않을것 같습니다.

**Comment by syohnet** [comment]
> * 자막검수 -> 유투브 싱크작업
> * 자막검수자와 유투브 싱크작업자는 같지 않아도 됨.

그럼 이거 포함해서 컨트리뷰션 가이드 작성해보죠!

**Comment by syohnet** [comment]
컨트리뷰션 가이드 작성 수준은 'git은 사용해봤으나, 컨트리뷰션과 PR 경험이 없는 사용자' 가 이해할 수 있을 정도로 생각했습니다. 더 많은 사람이 PR할 수 있도록 좀 더 쉽게 (git 설치, clone 설명 외부링크 포함)으로 조정해도 될 거 같고요. 

대략적 목차는 아래와 같습니다.
- 사전 준비
  - local setting (git clone)
  - 작업할 스크립트 작업 issue 생성 및 comment 
- 스크립트 수정 작업가이드 (용어집 참고,...)
- 작업완료 내용 PR 하기

위에서 빠진 내용이 있을까요?

**Comment by syohnet** [comment]
PR 은 고민이에요. 스크립트 단위로  branch 를 파서 작업하고 master에 PR 하는건 어떨까요?

**Comment by golony6449** [comment]
그런데 저 컨트리뷰션 가이드가 준비위를 위한 자료인가요? 아니면 그 외에도 자원봉사자까지 포함인가요?

준비위면은 branch 정도가 좋은것 같은데, 그외의 기여자분들까지 포함인거면 권한 문제 때문에 포크 후 PR로 하는것이 더 좋지 않을까요? 
겸사겸사 오픈소스 컨트리뷰션의 시작!: 문서 기여 라는 관점에서도 괜찮아 보이구요.

아 물론, 권한 문제가 없다면 레포지터리 내에서 브랜치로 나누는것이 처음 해보기에는 더 간단해서 좋을것 같기도 합니다.

**Comment by golony6449** [comment]
예시를 만든다면
기준을 git cli로 하는게 좋을까요? 아니면 소스트리나 깃헙 데스크톱 같은 GUI가 좋을까요?

**Comment by syohnet** [comment]
> 준비위면은 branch 정도가 좋은것 같은데, 그외의 기여자분들까지 포함인거면 권한 문제 때문에 포크 후 PR로 하는것이 더 좋지 않을까요?

누구나 기여할 수 있도록 작성하고자 합니다. repo 권한이 없는 분들을 위해 PR로 진행해보려고 하고요. 
제가 염두에 둔 방식은 fork -> PR from `forked origin/feature` branch to `pythonkr/master`  입니다.

> 겸사겸사 오픈소스 컨트리뷰션의 시작!: 문서 기여 라는 관점에서도 괜찮아 보이구요.

완전 좋습니다. 오픈소스 스프린트 ([스프린트 서울](https://www.sprintseoul.org)) 와 파이콘 한국 스프린트에서도 진행해보고 싶은 마음이 있습니다.

**Comment by syohnet** [comment]
> 예시를 만든다면
> 기준을 git cli로 하는게 좋을까요? 아니면 소스트리나 깃헙 데스크톱 같은 GUI가 좋을까요?

cli 명령어 까지만 예시로 생각했습니다.  [이 정도 수준](https://github.com/pythonkr/pyconkr#getting-started)으로요. 필요하다면 기존에 잘 나와있는 인터넷의 git tutorial 를 추가 참고 링크로 제공하고요.

**Comment by golony6449** [comment]
그러면 저도 `fork -> PR` 방식이 좋은 것 같습니다.
cli가 아무래도 클론, 커밋, 푸시 하기에는 간단할것 같아요. 이후 PR은 깃허브에서 해도 되니까요.

**Comment by syohnet** [comment]
그럼 PR 방식은 저대로 가고 github 이슈 생성에 대해 이야기해볼까요? 저는 간단히 issue template 만들어두고그에 맞게  작업자가 issue 만드는 방식을 생각해보았습니다. 이 방식대로 한다면 아래 내용들을 정리가 필요합니다. 
-  label 추가 (이름 뭘로 할지?)
- issue template 항목 무엇?

추가로 PR 템플릿도  있으면 좋겠네요. 체크리스트 겸사해서요. 예를 들어 아래 같이요
- [ ] 작업한 issue 넘버를 적으셨나요? 

이 방법 말고 다른 염두에 둔 방식이 있으신가요?  컨트리뷰션 할때 편했던 방식이라던가 아이디어를 알려주시면 감사하겠습니다

**Comment by golony6449** [comment]
말씀하신대로 이슈 발행이 가장 좋아보이기는 한데요.

뭐랄까... 작업을 하나씩 가져간다는 느낌이 강해서 뭔가 한번에 많이 해야될것 같은 느낌이 들수도 있을것 같습니다.

생각하는 방식은 커밋하듯이 좀 가볍게 할 수 있으면 좋겠다는 생각이 듭니다.
(아, 그런데 이건 `fork -> pr` 방식 자체가 가볍게 할수 있는게 아닐지도 모르겠네요.)

라벨은 그냥 파일명으로 하는게 어떨까요?

**Comment by syohnet** [comment]
> 뭐랄까... 작업을 하나씩 가져간다는 느낌이 강해서 뭔가 한번에 많이 해야될것 같은 느낌이 들수도 있을것 같습니다.
> 생각하는 방식은 커밋하듯이 좀 가볍게 할 수 있으면 좋겠다는 생각이 듭니다.
> (아, 그런데 이건 `fork -> pr` 방식 자체가 가볍게 할수 있는게 아닐지도 모르겠네요.)

확실히 부담이 될 수도 있겠네요. 1/3까지만 작업하고 PR merge 한다음에 다른 사람에게 넘기는 방식도 가능할까요? 스크립트의 어디 라인까지 작업되었는지 스크립트에 적고 PR 하는 방식이 생각나네요. 
예를 들면  `---------여기까지 검수하였습니다------` 라인을 중간에 추가한다던가요. 
중간에 나누는게 애매하네요. 

> 라벨은 그냥 파일명으로 하는게 어떨까요?

아, 깃헙 이슈 라벨 이야기였습니다. 지금 이슈라벨에 마땅한게 없어보여서요. 이슈라벨 안붙이고 assignee 로  관리해도 되고요.

**Comment by golony6449** [comment]
> 예를 들면 ---------여기까지 검수하였습니다------ 라인을 중간에 추가한다던가요.

오오 이거 좋은것 같습니다.
수정된 부분 중에 마지막 부분만 표기되면 나머지는 크게 불편할 것 없을것 같습니다.
검수 완료된 부분중에 잘못된 부분이 있는 경우는 다른 분이 샤샥 고치면 되는거니까요.


> 아, 깃헙 이슈 라벨 이야기였습니다. 지금 이슈라벨에 마땅한게 없어보여서요. 이슈라벨 안붙이고 assignee 로 관리해도 되고요.

아앗,, 그러군요. 혹시 나중에 다른 일감이 생길지도 모르니 `assignee` 할당이랑 `작업중` 라벨 정도면 괜찮지 않을까 생각합니다.

PR 템플릿에는 지금 저희 드라이브에 있는 것처럼 작업자, 예상 시간 정도 있으면 좋을것 같아요.
예상 시간 지나도 PR이 없으면 그냥 close 시킬 수 있게끔 하면 좋을것 같습니다.

**Comment by golony6449** [comment]
말씀 드리다보니 충돌방지나 중복 작업을 막기 위해서 이슈 발행도 필요할것 같네요.

다만 가이드 상에 해주신 만큼 `---------여기까지 검수하였습니다-----` 표기해서 보내주시면 됩니다.
라는 것을 표기해두면 좋을것 같습니다.

**Comment by syohnet** [comment]
@golony6449 이야기한 내용 토대로 본문 업데이트 했습니다. 할일을 나눠서 진행해볼까요? 하실 작업을 골라주십셔! 
p.s 충돌을 막기 위해 PR 로 작업해보시죠! 저는 중간중간 리뷰를 위해 미리 PR 열어두고 작업할게요.

**Comment by syohnet** [comment]
@golony6449  
- 작업해주신대로 PR은 리뷰어 지정 -> 리뷰하고 이상없으면 리뷰어가 `squash merge` & `delete branch` 하는 걸로 기준으로 작업하겠습니다. 
- 저는 forked  branch 에서 `draft`로 PR 넣어볼게요. 다른 방법 시도겸. 
- branch 명은 써주신 스타일에서 이슈넘버 추가해서 `이슈넘버_feature제목` 으로 하겠습니다!

**Comment by ohahohah** [comment]
넵 자막기여 PR 템플릿은 충분한 것 같습니다:) 작업해주신 내용을 바탕으로 저는 지금 PR guide 를 작성중이에요.

**Comment by ohahohah** [comment]
@golony6449 앗! PR template 파일명을 고쳐주실수있을까요? 나중에 다른 PR 템플릿이 추가되면 헷갈릴 거 같아요!

**Comment by syohnet** [comment]
contribution guide 작성 마무리되면 contribute file 하나로 합치는 건 어떻게 생각하시나요? README 에는  CONTRIBUTE.md 파일 링크만 걸어두고요. 
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by syohnet** [comment]
- [x] contribution guide 완료 #9 -> #28 
- [x] #19 작업되면 draft merge 하는게 어떨까요? 
@golony6449

**Comment by syohnet** [comment]
모든 작업이 완료되어 닫습니다.

**Comment by syohnet** [comment]
@all-contributors please add @ohahohah  for projectManagement.

**Comment by syohnet** [comment]
@all-contributors please add @ohahohah for projectManagement.
