### ISSUE TITLE
Repo Branch 관리

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#30]
- #3  작업이 마무리되면, repo 관리를 위한 branch 만 남겨두고, 다른 branch 를 정리하는 게 어떨까요? 
- repo관리용 branch는 지금 있는 `draft` branch 를 쭉 사용하는 건 어떨지요? 다만 이름은 좀 더 명확하게 바뀔 필요는 있어보입니다. (like `admin`) 이렇게 정리된다면 제가 생각하는 flow는 아래와 같습니다.
  1. Create an issue with admin label 
  2.  PR from `forked/admin_featured_branch`  to `draft` 
    - 같이 논의한 사람이 있으면 Reviewer 로 포함. 없으면 리뷰어 없이 이후 과정 진행
  3. After Review(or 리뷰안함), Merge
  4. Merge from `draft` to `master` & Merge (Assignee or Reviewer 가 진행)
  5. Close Issue

@golony6449 의견 부탁드립니다

**Comment by golony6449** [comment]
@ohahohah 
레포 관리용 브랜치가 자막기여 작업 이외의 작업을 말씀하시는 거죠?

저는 좋습니다. (사실 브랜치도 `정리해야지...` 하고 있던 참이라..)

그럼 지금 `draft` 반영 전 까지는 지금 처럼 작업 하고, 이후는 포크해서 PR 보내는 과정으로 작업하겠습니다.

**Comment by syohnet** [comment]
repo 관리  branch 전략은 wiki 로 남겨둘게요!

**Comment by syohnet** [comment]
완료되어 이슈를 닫습니다
