### ISSUE TITLE
자막 작업: 2019-pyconkr\day1\조인석_파이썬의 변수(강한 타입, immutable vs mutable, class vs instance).txt

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-script#37]
## 작업 내용

* 기여하시려는 파일 이름 (이슈 이름에도 추가해주세요. ^^): 2019-pyconkr\day1\조인석_파이썬의 변수(강한 타입, immutable vs mutable, class vs instance).txt

* 예상 마무리 일자: 2020.03.26.

## 생성 전 확인!

* 체크리스트를 확인해주세요. (체크하면서 확인하시면 편리합니다.)

- [x] 이슈 제목은 작업하려는 파일 이름으로 작성하셨나요?
- [x]  `assignee`를 자신으로 할당 하셨나요?
- [x]  `자막 스크립트 편집` 라벨이 추가되어있나요?

## 예시

* 아래의 스크린샷을 참고해주세요.

<img src="./script-in-repo.png" alt="주소" style="zoom:60%;" />

<img src="./example-complete.png" alt="예시" style="zoom:60%;" />

**Comment by syohnet** [comment]
@emscb  안녕하세요, 해당 이슈를 작업 중이신가요? 예상 마무리 일자를 업데이트 해주시면 감사하겠습니다. 업데이트가 없으면 1주일 후 3/25 에 본 이슈는 종료하도록 하겠습니다.

**Comment by syohnet** [comment]
이슈 종료하고 작업 재할당을 하도록 하겠습니다.
