### ISSUE TITLE
[Repo 관리] PR 전략 수정 (한번으로 master 에 반영, Rebase and Merge)

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#40]
현재 두 번의 PR을 거쳐 관리내용이 업데이트 되고 있습니다. 충돌을 막거나 보다 많은 사람들이 리뷰에 참여할 수 있게  하기 위해서였습니다. 하지만 언제나 관리의 품을 줄이기 위해서 바로 master 에 빠르게 반영하기 위해 한번의 PR 로 변경하고자 합니다.  
추가로 git commit log 가독성을 높이기 위해 `Rebase and merge`로 바꾸면 어떨까요?

## AS-IS
- 첫번째 PR :  forked branch -> draft  
- 두번째 PR : draft -> master 

## TO-BE
- 한번의 PR: forked branch -> master
- 오타수정처럼 작은 변경,  사전논의한 내용변경은 바로 master에 commit
-  [Rebase and Merge](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) / [Rebase and Merge 하는 방법](https://github.blog/2016-09-26-rebase-and-merge-pull-requests/)

**Comment by golony6449** [comment]
포크를 한 다음 PR을 하는거니 `draft`를 생략할 수 있고 로그도 깔끔하게 남으니 좋은 것 같습니다. 

사실 매번 그냥 별 생각없이 머지만 해왔는데, 편리한 기능인 듯 합니다.
유의할 점이 몇가지 있는것 같아서 문서 잘 읽어보고 머지하겠습니다 ^^

https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-Rebase-%ED%95%98%EA%B8%B0

**Comment by syohnet** [comment]
wiki 변경했습니다. https://github.com/pythonkr/pyconkr-script/wiki/%5BMaintainer%5D-Repository-관리-작업-순서/2eb7d61a16d726ef6eda8a90b9aa2eb98b23df72
