### ISSUE TITLE
PR template 만들기

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#5]
- 자막검수 contribution 을 위한 PR template 만들기

**Comment by syohnet** [comment]
PR에 [리뷰](https://github.com/pythonkr/pyconkr-script/pull/13) 남겨두었습니다~ 
제가 관련된 linked PR과 PR에 issue number mention 했습니다. 다음에 작성부탁드립니다~ :)

**Comment by golony6449** [comment]
앗, 감사합니다. ㅎㅎ

**Comment by syohnet** [comment]
@golony6449 넵 자막기여 PR 템플릿 내용은 작업해주신 것 충분한 것 같습니다:) PR template 파일명을 고쳐주실수있을까요? 나중에 다른 PR 템플릿이 추가되면 헷갈릴 거 같아요! 아까 리뷰할 때 까먹었네요ㅎㅎㅎㅎ
저는 지금 작업해주신 내용을 바탕으로 PR guide 를 작성중이에요.

**Comment by syohnet** [comment]
아하 깃헙은 pr template 이 하나군요! 이걸로 마무리하고 다른 내용 PR이 추가되면 그건 그때 생각해보는 걸로 하시죠!

**Comment by syohnet** [comment]
여러 템플릿 쓰는 방법이 좀 귀찮네용 https://blog.axosoft.com/enhancing-pull-request-descriptions-templates/

**Comment by syohnet** [comment]
반영사항 확인했습니다. 이슈 닫습니다.
