### ISSUE TITLE
스크립트편집 issue template 생성

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#6]
- template for 자막검수 assginee

**Comment by syohnet** [comment]
@golony6449  contribution guide 사전작업 작성하실때 이것도 같이 작업해주실 수 있을까요?

**Comment by golony6449** [comment]
@ohahohah 앗, 늦었습니다. 오늘 오프라고 하셔서 느긋하게 하려구 했었습니다.

논의했던것 토대로 일단 만든 다음에 수정사항 살짝 반영해서 `draft` 브랜치에 놔두겠습니다.

이 부분 보면서 다시 논의해봐요

**Comment by golony6449** [comment]
이슈 템플릿에 뭐가 필요할까 고민해봤습니다.

이슈 제목은 파일 이름으로하고, 내용에 예상 마무리 일자 정도 추가하면 될 것같아서 만들어두었습니다.

**Comment by golony6449** [comment]
github 내장 기능으로 추가했구요. 변경사항이 그렇게 많지 않아서, `draft`에 머지하고 원 브랜치는 삭제했습니다.

**Comment by ohahohah** [comment]
0c11e2680fd3a68b651bf50c2e761ec56a34d906

**Comment by syohnet** [comment]
PR에 리뷰 남겼습니다! 작업 감사합니다 :)

**Comment by golony6449** [comment]
리뷰 주신 부분 적용했습니다.
감사합니다. ^^
