### ISSUE TITLE
contribution guide -스크립트 편집 PR  

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#8]

**Comment by golony6449** [comment]
앗,, 어제 저녁에 간단하게 PR 템플릿도 만들어서 `draft`에 머지했습니다 ㅠㅠ
머지 하고 말씀드린다는걸 깜빡했네요 ㅠㅠ

**Comment by syohnet** [comment]
작업이 완료되어 이슈 종료합니다.

**Comment by syohnet** [comment]
@all-contributors please add @ohahohah for projectManagement.
