### ISSUE TITLE
contribution guide - 스크립트 편집

### ISSUE THREAD

**Issue by syohnet** [pythonkr/pyconkr-script#9]

**Comment by syohnet** [comment]
스크립트 일부만 편집했을 때 파일 내 표시하는  가이드가 필요합니다. 
참고. [pr template](https://github.com/pythonkr/pyconkr-script/blob/draft/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md#제출-전-다시한번)

**Comment by golony6449** [comment]
@ohahohah 

> 검수한 스크립트 내용 앞에 줄을 추가해 (여기부터 검수 시작) 을 적어주시고 검수한 내용 마지막 줄에 (여기까지 검수완료) 를 추가해 적어주세요.

이 부분을 PR 템플릿에 추가했는데, 스크린샷으로 예시도 추가하는게 좋을까요?

앗, 추가가 필요한 부분을 찾았습니다.
#24 작성해 주신 `pr-guide.md`를 참고해 추가해보았습니다.
